### PR TITLE
Python package

### PR DESCRIPTION
**Pull request by tgoelles**
In order to work on the front-end I want to cleanly import the code.
Therefore, and for a future release on PYPI I created a Python package.
I called it "biosnicar".

Before releasing it there we should decide what is actually part of the package and what are just associated tools. Also maybe consider including a CLI which could be a part of the package. I don't have the overview yet what is really needed.

I also added a Changelog.rst which should follow the semantic versioning principles (linked there).
In combination with this I added bump2version config file and the dependency. With this tool it is easy to change version number. For example: $ bump2version minor 
this would increase the version number to  v2.1.0 in all relevant places and crate a git tag.

For more details see the Changelog.

The whole path handling also needs an overhaul. The best would be to use the Path object from pathlib of the standard library. 

If this PR is accepted I can start on the front-end.

### CODE REVIEW

**Comment by tgoelles** [comment]
gh actions test now work. But it seems like the docu of the functions is broken. So this needs to be fixed before merging

**Comment by tgoelles** [comment]
Hi @jmcook1186 , just finished. so its ready for review

**Comment by jmcook1186** [comment]
Great - thank you this looks like a lot of work! I'll get to reviewing it this afternoon.

**Review by jmcook1186 — APPROVED** [review]
This looks great, thanks a lot for the monster PR!

**Pull request merged**
